# Generated by Django 4.2.6 on 2023-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_categoria_alter_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.BooleanField(default=False),
        ),
    ]
